# tests/funciontal/test_connectivity.py
import pytest
import requests
from collections import Counter
from tests.utils import now_str, extract_response_host

pytestmark = pytest.mark.connectivity

# ---- Constants
SAMPLE_COUNT = 20
IMBALANCE_THRESHOLD_PERCENT = 80
REQUEST_TIMEOUT = 2

# ---- Tests
def test_alb_http_access(alb_url):
    """[Smoke] ALB HTTP 접근 가능 여부 확인"""
    try:
        resp = requests.get(alb_url, timeout=5) # ALB에 접속 자체가 가능한지? 
        assert resp.status_code == 200, "Non-200 HTTP status code returned"
    except Exception as e:
        pytest.fail(f"Failed to connect to ALB: {e}")

def test_target_group_has_healthy_instances(elbv2_client, tg_arn):
    """[Smoke] Target Group 내 Healthy 인스턴스 존재 여부"""
    if not tg_arn:
        pytest.skip("TG ARN is not configured")

    resp = elbv2_client.describe_target_health(TargetGroupArn=tg_arn)
    healthy_count = sum(
        1 for t in resp["TargetHealthDescriptions"]
        if t["TargetHealth"]["State"] == "healthy"
    )

    print(f"\n[{now_str()}] [INFO] [TG] Healthy instances: {healthy_count}")
    assert healthy_count >= 2, "Less than 2 healthy instances detected"

def test_load_is_distributed_across_instances(alb_url):
    """[Smoke] Response가 여러 인스턴스로부터 균형되게 오는지 """
    hosts = []

    print(
        f"\n[{now_str()}] [INFO] [LB] Load distribution test started "
        f"(samples={SAMPLE_COUNT})",
        end=" ",
        flush=True,
    )

    for _ in range(SAMPLE_COUNT):
        try:
            resp = requests.get(
                alb_url,
                headers={"Connection": "close"},
                timeout=REQUEST_TIMEOUT,
            )
            host = extract_response_host(resp.text)
            if host:
                hosts.append(host)
                print(".", end="", flush=True)
        except Exception:
            print("x", end="", flush=True)

    assert len(hosts)>0, "No successful responses from ALB."
    unique_hosts = set(hosts)
    assert len(unique_hosts) >= 2, "Responses were generated by a single instance."

    counts = Counter(hosts)
    total = len(hosts)

    print(f"\n[{now_str()}] [REPORT] [LB] Response distribution: {dict(counts)}")

    for host, count in counts.items():
        pct = (count / total) * 100
        assert pct < IMBALANCE_THRESHOLD_PERCENT, (
            f"Traffic imbalance detected: {host} received {pct:.0f}%"
        )

def test_instances_are_distributed_across_multiple_azs(elbv2_client, ec2_client, tg_arn):
    """[Smoke] Healthy 인스턴스가 Multi-AZ로 배포되어 있는지 검증"""
    if not tg_arn:
        pytest.skip("TG ARN is not configured")

    tg_health = elbv2_client.describe_target_health(TargetGroupArn=tg_arn)
    healthy_ids = [
        t["Target"]["Id"]
        for t in tg_health["TargetHealthDescriptions"]
        if t["TargetHealth"]["State"] == "healthy"
    ]

    assert healthy_ids, "No healthy instances found"

    ec2_resp = ec2_client.describe_instances(InstanceIds=healthy_ids)
    detected_azs = {
        instance["Placement"]["AvailabilityZone"]
        for r in ec2_resp["Reservations"]
        for instance in r["Instances"]
    }

    print(f"\n[{now_str()}] [INFO] [AZ] Detected AZs: {detected_azs}")
    assert len(detected_azs) >= 2, "Instances are not distributed across multiple AZs"
